---

collections:
  - name: ansible.posix
    version: 1.3.0
  - name: awx.awx
    version: 20.1.0
  - name: community.general
    version: 4.6.1
  - name: community.vmware
    version: 2.2.0
  - name: freeipa.ansible_freeipa
    version: 1.6.2
  - name: redhat_cop.controller_configuration
    version: 2.1.3
  - name: redhat_cop.aap_utilities
    version: 2.1.0
