---
collections:
  - name: amazon.aws
  - name: ansible.eda
    version: 1.4.5
  - name: ansible.posix
    version: 1.5.4
  - name: awx.awx
    version: 23.8.0
  - name: community.crypto
    version: 2.17.1
  - name: community.general
    version: 8.3.0
  - name: community.vmware
    version: 4.1.0
  - name: containers.podman
    version: 1.12.0
  - name: dynatrace.oneagent
    version: 1.0.3
  - name: freeipa.ansible_freeipa
    version: 1.12.1
  - name: kubernetes.core
    version: 3.0.0
  - name: microsoft.sql
    version: 2.2.2
  - name: redhat_cop.controller_configuration
    version: 2.3.1
  - name: redhat.rhel_system_roles
    version: 1.88.9
  - name: redhat.rhel_idm
    version: 1.12.1
  - name: vmware.vmware_rest
    version: 3.0.0
  - name: myllynen.ansible_packer
    source: https://github.com/myllynen/ansible-packer
    # version: master
    type: git
  - name: myllynen.rhel-ansible-roles
    source: https://github.com/myllynen/rhel-ansible-roles
    # version: v0.5.7
    type: git
  - name: myllynen.rhel_image
    source: https://github.com/myllynen/rhel-image
    type: git
  # - name: myllynen.satellite-automation
  #   source: https://github.com/myllynen/satellite-automation
  #   # version: master
  #   type: git
  - name: redhat.satellite
    version: 4.0.0
  - name: redhat.satellite_operations
    version: 2.1.0
  - name: infra.aap_utilities
    version: 2.3.0
