---

collections:
  - name: ansible.eda
    version: 1.3.8
  - name: ansible.posix
    version: 1.4.0
  - name: awx.awx
    version: 21.4.0
  - name: community.general
    version: 6.1.0
  - name: community.vmware
    version: 2.2.0
  - name: freeipa.ansible_freeipa
    version: 1.6.2
  - name: microsoft.sql
    version: 1.1.0
  - name: redhat_cop.controller_configuration
    version: 2.1.3
  - name: redhat.rhel_system_roles
    version: 1.19.3
  - name: redhat.rhel_idm
    version: 1.8.4
  - name: vmware.vmware_rest
    version: 2.2.0
  - name: myllynen.ansible_packer
    source: https://github.com/myllynen/ansible-packer
    # version: master
    type: git
  - name: myllynen.rhel-ansible-roles
    source: https://github.com/myllynen/rhel-ansible-roles
    version: 'v0.5.7'
    type: git
  - name: myllynen.satellite-automation
    source: https://github.com/myllynen/satellite-automation
    # version: master
    type: git
  - name: redhat.satellite
    version: 3.7.0
  - name: infra.aap_utilities
    version: 2.2.4
