---

collections:
  - name: ansible.posix
    version: 1.3.0
  - name: awx.awx
    version: 21.4.0
  - name: community.general
    version: 4.6.1
  - name: community.vmware
    version: 2.2.0
  - name: freeipa.ansible_freeipa
    version: 1.6.2
  - name: redhat_cop.controller_configuration
    version: 2.1.3
  - name: redhat.rhel_system_roles
    version: 1.16.2
  - name: microsoft.sql
    version: 1.1.0
