---

collections:
  - name: ansible.posix
    version: 1.3.0
  - name: awx.awx
    version: 19.4.0
  - name: community.general
    version: 4.3.0
  - name: community.vmware
    version: 1.17.0
  - name: freeipa.ansible_freeipa
    version: 1.6.3
  - name: redhat_cop.controller_configuration
    version: 2.1.1
