---
collections:
  - name: amazon.aws
  - name: ansible.eda
  - name: ansible.posix
    # version: 1.5.4
  - name: awx.awx
    # version: 23.8.0
  - name: ansible.controller
  - name: ansible.eda
  - name: ansible.hub
  - name: ansible.platform
  - name: community.crypto
    #  version: 2.17.1
  - name: community.general
    # version: 8.3.0
  - name: community.vmware
    # version: 4.1.0
  - name: containers.podman
    # version: 1.12.0
  - name: dynatrace.oneagent
    # version: 1.0.3
  - name: infra.aap_configuration
  - name: kubernetes.core
    # version: 3.0.0
  - name: microsoft.sql
    # version: 2.2.2
  - name: redhat.rhel_system_roles
    # version: 1.23.0
  - name: redhat.rhel_idm
    # version: 1.14.2
  - name: vmware.vmware_rest
    # version: 3.0.0
  - name: myllynen.ansible_packer
    source: https://github.com/myllynen/ansible-packer
    # version: master
    type: git
  - name: myllynen.rhel-ansible-roles
    source: https://github.com/myllynen/rhel-ansible-roles
    # version: v0.5.7
    type: git
  - name: myllynen.rhel_image
    source: https://github.com/myllynen/rhel-image
    type: git
  - name: redhat.satellite
    # version: 4.0.0
  - name: redhat.satellite_operations
    # version: 2.1.0
