---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgt-eu-arrow-lab-setup
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/RedHatNordicsSA/cool-lab.git
    targetRevision: arrowlab
    path: ocp-configs/gitops/mgmt-eu-arrow-lab/argocd-applications
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      allowEmpty: true
