---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-operator
spec:
  project: default
  source:
    repoURL: https://github.com/RedHatNordicsSA/cool-lab.git
    targetRevision: HEAD
    path: ocp-configs/gitops/rh-ocpmgt/advanced-cluster-management/operator/overlays/release-2.9
  destination:
    server: https://kubernetes.default.svc
    namespace: open-cluster-management
  syncPolicy:
    automated:
      allowEmpty: true
