---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: advanced-cluster-security-instance
spec:
  project: default
  source:
    repoURL: https://github.com/RedHatNordicsSA/cool-lab.git
    targetRevision: HEAD
    path: ocp-configs/gitops/rh-ocpmgt/advanced-cluster-security-operator/instance/overlays/default
  destination:
    server: https://kubernetes.default.svc
    namespace: stackrox
  syncPolicy:
    automated:
      allowEmpty: true
