---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: group-sync-instance
spec:
  project: default
  source:
    repoURL: https://github.com/RedHatNordicsSA/cool-lab.git
    targetRevision: HEAD
    path: ocp-configs/gitops/rh-ocpmgt/group-sync/instance/overlays/ldap
  destination:
    server: https://kubernetes.default.svc
    namespace: group-sync-operator
  syncPolicy:
    automated:
      allowEmpty: true
