---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth-ldap
spec:
  project: default
  source:
    repoURL: https://github.com/RedHatNordicsSA/cool-lab.git
    targetRevision: HEAD
    path: ocp-configs/gitops/rh-ocpmgt/oauth/overlays/ldap
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-cnv
  syncPolicy:
    automated:
      allowEmpty: true
