---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-operator
spec:
  project: default
  source:
    repoURL: https://github.com/RedHatNordicsSA/cool-lab.git
    targetRevision: HEAD
    path: ocp-configs/gitops/rh-ocpmgt/openshift-cert-manager-operator/operator/overlays/stable-v1.14
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager-operator
  syncPolicy:
    automated:
      allowEmpty: true
