---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odf-operator
spec:
  project: default
  source:
    repoURL: https://github.com/RedHatNordicsSA/cool-lab.git
    targetRevision: HEAD
    path: ocp-configs/gitops/rh-ocpmgt/openshift-data-foundation-operator/operator/overlays/stable-4.14
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-storage
  syncPolicy:
    automated:
      allowEmpty: true
