---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quay-container-security-operator
spec:
  project: default
  source:
    repoURL: https://github.com/RedHatNordicsSA/cool-lab.git
    targetRevision: HEAD
    path: ocp-configs/gitops/rh-ocpmgt/quay-container-security-operator/overlays/stable-3.10
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  syncPolicy:
    automated:
      allowEmpty: true
