---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'alpha'
      - op: add
        path: /spec/config
        value:
          env:
            - name: WATCH_NAMESPACE
              value: ''
    target:
      kind: Subscription
      name: group-sync-operator
