---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  vars:
    aap_username: admin
    aap_password: "{{ vault_aap_admin_password }}"
    aap_validate_certs: false
  tasks:
    - name: Include vars from configs directory
      ansible.builtin.include_vars:
        dir: "{{ aap_configs_dir | default((lookup('env', 'AAP_CONFIGS_DIR') == '') | ternary('./aap_configs_dir', lookup('env', 'AAP_CONFIGS_DIR'))) }}"
        ignore_files: [controller_config.yml.template]
        extensions: [yml]
      tags:
        - always

    - name: Call dispatch role
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
...
