---

- name: Build RHEL template with Packer
  hosts: all
  become: true
  tasks:

    - name: build rhel template for vmware
      vars:
        vsphere_server: arw-vcenter-21.arrowdemo.se
        vcenter_datacenter: KISTA-DC
        vcenter_folder: KISTA-DC/Redhat
        vcenter_cluster: ARROWLAB
        vcenter_resource_pool:
        vcenter_datastore: SVC-LUN-1
        vsphere_network: vlan2102

        packer_builder: vmware
        packer_target: rhel_8_5
        boot_password: "{{ cloud_user_password }}"
        root_password: "{{ cloud_user_password }}"
        partitioning: auto
        disable_ipv6: true
        # security_profile: cis_server_l1
        image_name: rhel_8_5_image
        root_ssh_key: >
          ssh-ed25519
          AAAAC3NzaC1lZDI1NTE5AAAAIHV4O/qEctm+YmAY/o0aKk+sgxbFhLMsNN1m4j8FNKSF
          admin@coollab
        # disk_size: 4096
        iso:
          rhel_8_5:
            url: "file:///home/itengval/VirtualMachines/rhel-8.5-x86_64-dvd.iso"
            checksum: sha256:1f78e705cd1d8897a05afa060f77d81ed81ac141c2465d4763c0382aa96cadd0
      include_role:
        name: ansible-packer
