---

- name: Build RHEL template with Packer
  hosts: all
  become: true
  tasks:

    - name: build rhel template for vmware
      vars:
        vcenter_datacenter: KISTA-DC
        vcenter_folder: KISTA-DC/Redhat
        vcenter_cluster: ARROWLAB
        vcenter_resource_pool:
        vcenter_datastore: SVC-LUN-2
        vcenter_network: vlan2102
        vcenter_convert_to_template: true

        do_cleanup: true

        packer_builder: vmware
        # packer_target: rhel_8_7
        packer_target: rhel_9_2
        packer_binary: packer
        vcenter_insecure_connection: true
        boot_password: "{{ cloud_user_password }}"
        root_password: "{{ cloud_user_password }}"
        partitioning: auto
        disable_ipv6: true
        boot_parameters: net.ifnames.prefix=net quiet systemd.show_status=yes
        ntp_servers: time.cloudflare.com
        timezone: Europe/Helsinki
        keyboard: fi
        disk_size: 30720

        create_admin: true
        admin_user:
          uid: 4444
          gid: 4444
          name: cloud-user
          group: cloud-user
          groups: wheel
          home: /home/cloud-user
          gecos: Admin User
          ssh_key: >
            ssh-ed25519
            AAAAC3NzaC1lZDI1NTE5AAAAIHV4O/qEctm+YmAY/o0aKk+sgxbFhLMsNN1m4j8FNKSF
            admin@coollab
          passwordless_sudo: true

        root_permit_local: true

        # security_profile: cis_server_l1
        image_name: rhel_9_2_image
        # image_name: rhel_8_7_image
        root_ssh_key: >
          ssh-ed25519
          AAAAC3NzaC1lZDI1NTE5AAAAIHV4O/qEctm+YmAY/o0aKk+sgxbFhLMsNN1m4j8FNKSF
          admin@coollab
        # disk_size: 4096
        iso:
          rhel_9_2:
            # yamllint disable-line rule:line-length
            url: "file:///home/itengval/VirtualMachines/rhel-9.2-x86_64-dvd.iso"
            # yamllint disable-line rule:line-length
            checksum: sha256:a18bf014e2cb5b6b9cee3ea09ccfd7bc2a84e68e09487bb119a98aa0e3563ac2
          rhel_8_7:
            # yamllint disable-line rule:line-length
            url: "file:///home/itengval/VirtualMachines/rhel-8.7-x86_64-dvd.iso"
            # yamllint disable-line rule:line-length
            checksum: sha256:a6a7418a75d721cc696d3cbdd648b5248808e7fef0f8742f518e43b46fa08139
      include_role:
        name: myllynen.ansible_packer.ansible_packer
