---

- name: Build RHEL edge template with Packer
  hosts: all
  become: true
  tasks:

    - name: build rhel edge template for vmware
      vars:
        vcenter_datacenter: KISTA-DC
        vcenter_folder: KISTA-DC/Redhat
        vcenter_cluster: ARROWLAB
        vcenter_resource_pool:
        vcenter_datastore: SVC-LUN-2
        vcenter_network: vlan2102
        vcenter_convert_to_template: true

        do_cleanup: true
        # do_cleanup: false

        packer_builder: vmware
        # packer_builder: qemu
        # qemu_binary: /usr/bin/qemu-kvm
        # output_directory: /home/itengval/VirtualMachines/packer_out
        packer_target: rhel-edge_9_1
        packer_target_pretty: RHEL9 Edge
        packer_binary: packer
        vcenter_insecure_connection: true
        boot_password: "{{ cloud_user_password }}"
        root_password: "{{ cloud_user_password }}"
        partitioning: auto
        disable_ipv6: true
        boot_parameters: net.ifnames.prefix=net quiet systemd.show_status=yes
        ntp_servers: time.cloudflare.com
        timezone: Europe/Helsinki
        keyboard: fi
        disk_size: 10240
        ostree_url: http://10.128.1.177:8080/repo/
        ostree_href: rhel/9/x86_64/edge


        create_admin: true
        admin_user:
          uid: 4444
          gid: 4444
          name: cloud-user
          group: cloud-user
          groups: wheel
          home: /home/cloud-user
          gecos: Admin User
          ssh_key: >
            ssh-ed25519
            AAAAC3NzaC1lZDI1NTE5AAAAIHV4O/qEctm+YmAY/o0aKk+sgxbFhLMsNN1m4j8FNKSF
            admin@coollab
          passwordless_sudo: true

        root_permit_local: true

        # security_profile: cis_server_l1
        image_name: rhel_edge_9_1_image
        root_ssh_key: >
          ssh-ed25519
          AAAAC3NzaC1lZDI1NTE5AAAAIHV4O/qEctm+YmAY/o0aKk+sgxbFhLMsNN1m4j8FNKSF
          admin@coollab
        # disk_size: 4096
        iso:
          rhel-edge_9_1:
            # yamllint disable-line rule:line-length
            url: "file:///home/itengval/VirtualMachines/rhel-baseos-9.1-x86_64-dvd.iso"
            # yamllint disable-line rule:line-length
            checksum: sha256:d9dcae2b6e760d0f9dcf4a517bddc227d5fa3f213a8323592f4a07a05aa542a2

      include_role:
        name: myllynen.ansible_packer.ansible_packer
