---

- name: "Ensure VM state"
  hosts: localhost
  vars:
    ns: rh-infra
    net_name: vlan3103-rh-infra
  tasks:

    - name: "Create Namespace {{ ns }}"
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        state: present
        name: "{{ ns }}"
      when: vm_state == "present"
      ignore_errors: true # it might be OCP SA does not have permissions for this

    - name: Ensure VM is "{{ vm_state }}"
      redhat.openshift_virtualization.kubevirt_vm:
        state: "{{ vm_state | default('present')}}"
        name: "{{ short_name }}"
        namespace: "{{ ns }}"
        labels:
          rh-infra: "aap-generated"
        instancetype:
          name: "{{ instancetype | default('u1.small')}}"
        preference:
          name: "{{ vm_preference | default('fedora')}}"
        run_strategy: Always
        data_volume_templates:
          - metadata:
              name: "{{ short_name }}-volume"
            spec:
              sourceRef:
                kind: DataSource
                name: "{{ vm_data_source | default('rhel9')}}"
                namespace: openshift-virtualization-os-images
              storage:
                resources:
                  requests:
                    storage: "{{ vm_disk_gb | default('32')}}Gi"
                storageClassName: ocs-storagecluster-ceph-rbd-virtualization
        spec:
          domain:
            devices:
              autoattachPodInterface: false
              disks:
              - bootOrder: 1
                name: rootdisk
              interfaces:
                # - name: default
                #   masquerade: {}
                - name: "{{ short_name }}-bridge-network"
                  model: virtio
                  bridge: {}
                  state: up
          networks:
            # - name: default
            #   pod: {}
            - name: "{{ short_name }}-bridge-network"
              multus:
                networkName: "{{ net_name }}"
          subdomain: headless
          volumes:
            - dataVolume:
                name: "{{ short_name }}-volume"
              name: rootdisk
            - cloudInitNoCloud:
                userData: |-
                  #cloud-config
                  users:
                    - default
                    - name: admin
                      groups: wheel
                      sudo: ALL=(ALL) NOPASSWD:ALL
                      ssh_authorized_keys: 
                        - "{{ lab_admin_ssh_pubkey }}"
                    - name: root
                      ssh_authorized_keys: 
                        - "{{ lab_admin_ssh_pubkey }}"
                  chpasswd:
                    expire: false
                  ssh_authorized_keys: 
                    - "{{ lab_admin_ssh_pubkey }}"
                #   rh_subscription:
                #     username: "{{ vault_rh_subs_username }}"
                #     password: "{{ vault_rh_subs_password }}"
                #     auto-attach: True
                #    package_upgrade: true
                # networkData: |-
                #   #network-config
                #   network:
                #     version: 2
                #     ethernets:
                #       eth0:
                #         addresses:
                #           - 10.3.103.12/24
                #         gateway: 10.3.103.1
                #         nameservers:
                #           addresses:
                #             - "{{ ipaserver_master_ip }}"
                #             - "{{ ipaserver_replica_ip }}"
                #         routes:
                #           - to: 0.0.0.0/0
                #             via: 10.3.103.1
              name: cloudinit
        wait: true
        register: vm

    - name: Wait for VM IP to be populated
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: "{{ short_name }}"
        namespace: "{{ ns }}"
      register: deploy_collection_vmi
      retries: 60
      delay: 10
      until: (deploy_collection_vmi.resources[0].status.interfaces[0]['ipAddress'] | default('')) | length > 0
      when: vm_state == "present"

    - name: VM address
      debug:
        msg: "VM {{ short_name }} IP address is {{ deploy_collection_vmi.resources[0].status.interfaces[0]['ipAddress'] }}"
        var: vm
      when: vm_state == "present"

    - name: Create tower inventory
      ansible.controller.inventory:
        name: "Temporary Inventory"
        description: "Temporary inventory for hosts to be created"
        organization: "Default"
        state: present
        validate_certs: false
      when:
        - use_aap_inventory
        - vm is succeeded

    - name: Add tower host
      ansible.controller.host:
        name: "{{ short_name }}"
        inventory: "Temporary Inventory"
        state: present
        validate_certs: false
        variables:
          # ansible_host: "{{ vm.instance.ipv4 }}"
          ansible_host: "{{ deploy_collection_vmi.resources[0].status.interfaces[0]['ipAddress'] }}"
      when:
        - use_aap_inventory
        - vm is succeeded

    - name: Add host to temporary group for new vms
      ansible.controller.group:
        name: new_vms
        inventory: "Temporary Inventory"
        hosts:
          - "{{ short_name }}"
        validate_certs: false
        preserve_existing_hosts: true
      when:
        - use_aap_inventory
        - vm is succeeded

    - name: Wait for Virtual Machine to boot up and become responsive to SSH
      wait_for:
        port: 22
        host: "{{ vm.instance.ipv4 }}"
        search_regex: OpenSSH
        delay: 10
        timeout: 600
      when: vm is succeeded

    # - name: "Create Service"
    #   tags:
    #     - svc
    #   kubernetes.core.k8s:
    #     state: "{{ vm_state | default('present')}}"
    #     definition:
    #       kind: Service
    #       apiVersion: v1
    #       metadata:
    #         name: "{{ short_name }}"
    #         namespace: "{{ ns }}"
    #       spec:
    #         ports:
    #           - protocol: TCP
    #             port: 9090
    #             targetPort: 9090
    #             name: cockpit
    #           - protocol: TCP
    #             port: 443
    #             targetPort: 443
    #             name: https
    #         type: ClusterIP
    #         selector:
    #           kubevirt.io/domain: "{{ short_name }}"
    #
    # - name: "Create Route for https"
    #   tags:
    #     - routes
    #   kubernetes.core.k8s:
    #     state: "{{ vm_state | default('present')}}"
    #     definition:
    #       kind: Route
    #       apiVersion: route.openshift.io/v1
    #       metadata:
    #         name: "{{ short_name }}"
    #         namespace: "{{ ns }}"
    #       spec:
    #         to:
    #           kind: Service
    #           name: "{{ short_name }}"
    #           weight: 100
    #         port:
    #           targetPort: 443
    #         wildcardPolicy: None
    #
    # - name: "Create Route for cockpit"
    #   tags:
    #     - routes
    #   kubernetes.core.k8s:
    #     state: "{{ vm_state | default('present')}}"
    #     definition:
    #       kind: Route
    #       apiVersion: route.openshift.io/v1
    #       metadata:
    #         name: "{{ short_name }}-cockpit"
    #         namespace: "{{ ns }}"
    #       spec:
    #         to:
    #           kind: Service
    #           name: "{{ short_name }}"
    #           weight: 100
    #         port:
    #           targetPort: 9090
    #         wildcardPolicy: None
