---

- name: Create bastion host VM from the template
  hosts: localhost
  gather_facts: false
  vars:
    state: poweredon
  tasks:
    - name: Clone the template
      vmware_guest:
        hostname: "{{ vcenter_credentials.hostname }}"
        username: "{{ vcenter_credentials.username }}"
        password: "{{ vcenter_credentials.password }}"
        validate_certs: false
        name: bastion.coollab
        template: rhel_8_5_image
        datacenter: "{{ vcenter_datacenter }}"
        folder: "{{ vcenter_folder }}"
        state: "{{ state }}"
        cluster: "{{ vcenter_cluster }}"
        wait_for_ip_address: true
        hardware:
          memory_mb: 2048
          num_cpus: 2
          num_cpu_cores_per_socket: 1
        networks:
          - name: RH-seg-2991
            type: dhcp
            # type: static
            # ip: 10.128.1.3
            # netmask: 255.255.255.0
            # gateway: 10.128.1.1
            wait_for_ip_address_timeout: 60
            connected: yes
            start_connected: yes
