---

- name: Playbook to manage host groups
  hosts: rh-idm-01.cool.lab
  vars:
    hostgroup_state: present
  tasks:

    - name: ensure hostgroup exists
      freeipa.ansible_freeipa.ipahostgroup:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
      loop: "{{ hostgroups }}"

    - name: ensure hosts in hostgroups
      freeipa.ansible_freeipa.ipahostgroup:
        name: "{{ item.name }}"
        host: "{{ item.hosts }}"
        action: member
        state: "{{ hostgroup_state }}"
      loop: "{{ hostgroups }}"
