---
- name: Use metrics system role to configure PCP metrics recording
  hosts: mssql
  vars: 
    metrics_retention_days: 7
    metrics_from_mssql: yes
    mssql_agent_trusted: 
    mssql_agent_username: 
    mssql_agent_password: 

  roles: 
    - redhat.rhel_system_roles.metrics

- name: Use metrics system role to configure Grafana
  hosts: "{{ monitor_name }}" 
  vars:
    metrics_monitored_hosts:  [mssql]
    
  roles: 
    - redhat.rhel_system_roles.metrics

- name: ensure remote monitoring is possible
  hosts: mssql
  tasks:

  - name: Make sure pmproxy is running 
    service: 
      name: pmproxy
      state: started
      enabled: yes