---


- name: Nuke VM from VMware
  connection: local
  hosts: localhost
  gather_facts: false
  tasks:

    - name: print out the target
      debug:
        msg: |
          "About to delete VM {{ short_name | mandatory }}"
          "from datacenter {{ vcenter_datacenter }}"
          "in cluster {{ vcenter_cluster }}."

    - name: nuke the vm
      community.vmware.vmware_guest:
        name: "{{ short_name | mandatory }}"
        state: absent
        hostname: "{{ vcenter_credentials.hostname }}"
        username: "{{ vcenter_credentials.username }}"
        password: "{{ vcenter_credentials.password }}"
        validate_certs: false
        datacenter: "{{ vcenter_datacenter }}"
        folder: "{{ vcenter_folder }}"
        cluster: "{{ vcenter_cluster }}"
        force: true

