---


- name: Nuke VM from VMware
  connection: local
  hosts: localhost
  gather_facts: false
  tasks:

    - name: print out the target
      debug:
        msg: |
          "About to delete VM {{ short_name | mandatory }}"
          "from datacenter {{ vcenter_datacenter }}"
          "in cluster {{ vcenter_cluster }}."

    - name: Use vmware credentials from vault if set there, otherwise from AAP credentials
      set_fact:
        vcenter_credentials:
          hostname: '{{ lookup("env", "VMWARE_HOST") }}'
          username: '{{ lookup("env", "VMWARE_USER") }}'
          password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
      when:
        - vcenter_credentials.vcenter_server is not defined
        - vcenter_credentials.vcenter_username is not defined
        - vcenter_credentials.vcenter_password is not defined

    - name: nuke the vm
      community.vmware.vmware_guest:
        name: "{{ short_name | mandatory }}"
        state: absent
        hostname: "{{ vcenter_credentials.vcenter_server }}"
        username: "{{ vcenter_credentials.vcenter_username }}"
        password: "{{ vcenter_credentials.vcenter_password }}"
        validate_certs: false
        datacenter: "{{ vcenter_datacenter }}"
        folder: "{{ vcenter_folder }}"
        cluster: "{{ vcenter_cluster }}"
        force: true

