---


- name: Nuke VM
  hosts: all
  vars:
    use_inventory_for_hostname: false
  tasks:

    - name: unregister from IdM
      vars:
        state: absent
      include_role:
        name: freeipa.ansible_freeipa.ipaclient
      tags: idm
      ignore_errors: true

    - name: unregister insights
      command: insights-client --unregister
      args:
        creates: /etc/insights-client/.unregistered
      tags: insights
      ignore_errors: true

    - name: unsubscribe from Red Hat
      redhat_subscription:
        state: absent
      tags: subs
      ignore_errors: true

    - name: Get the short name from inventory
      set_fact:
        short_name: "{{ inventory_hostname | regex_search('^[^._]*') }}"
      when: use_inventory_for_hostname

- name: Nuke VM from VMware
  import_playbook: ensure-vm-state.yml
  vars:
    state: absent
    vm_name: "{{ short_name | mandatory }}"
