---

- name: Cleanup host from AAP inventory
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    inventory_name: Temporary Inventory

  tasks:

    - name: Delete vm from AAP temporary inventory
      ansible.controller.host:
        name: "{{ short_name | mandatory }}"
        inventory: "{{ inventory_name }}"
        state: absent
        validate_certs: false
