---
- name: Build RHEL image with Image Builder
  hosts: rh-imgbuilder-09.cool.lab
  become: true
  vars:
    rhel_image_do_setup: false
    rhel_image_do_build: true
    rhel_image_do_cleanup: false
    rhel_image_update_host: false
    rhel_image_create_user: false
    rhel_image_builder_user: ikke

    rhel_image_git_remote_repo: https://github.com/RedHatNordicsSA/cool-lab.git
    rhel_image_git_repo_checkout: main
    rhel_image_blueprint: base-image
    rhel_image_output_type: vmdk
    rhel_image_size_kb: 30720
    # Optional image filename to use instead of UUID
    #rhel_image_filename: ci-daily-image.qcow2

    # This is on the build host
    # rhel_image_download_dir: /tmp/images
    # Fetch from the build host
    rhel_image_fetch_image: false
    # This is where this playbook runs
    rhel_image_fetch_directory: /tmp
    rhel_image_remote_delete: false
  roles:
    - myllynen.rhel_image.rhel_image
