---
- hosts: all
  vars:
    satellite: rh-satellite-01.eu.arrow.lab
    org: Red_Hat
    rhc_state: reconnect
    rhc_organization: "{{ org }}"
  tasks:

    - name: Install dependency package python requests
      package:
        name: python3-requests

    - name: unregister insights
      command: insights-client --unregister
      args:
        creates: /etc/insights-client/.unregistered
      ignore_errors: true

    - name: unsubscribe from Red Hat
      community.general.redhat_subscription:
        state: absent

    - name: Clean subsriptions
      ansible.builtin.shell:
        cmd: "subscription-manager clean"

    - name: Generate satellite registration command for client
      redhat.satellite.registration_command:
        username: "{{ vault_satellite_username }}"
        password: "{{ vault_satellite_password }}"
        server_url: "https://{{ satellite }}"
        validate_certs: false
        insecure: true
        force: true
        activation_keys:
          - "RHEL{{ ansible_facts['distribution_major_version'] }}"
      register: command

    - debug:
        var: command.registration_command

    - name: Perform registration
      ansible.builtin.shell:
        cmd: "{{ command.registration_command }}"
