---
- hosts: all
  vars:
    org: Red_Hat
    rhc_state: reconnect
    rhc_organization: "{{ org }}"
    ini_path: "{{ lookup('env', 'FOREMAN_INI_PATH') }}"
  tasks:


    - name: Use satellite credentials from from vault
      set_fact:
        host: "{{ satellite_server_url }}"
        username: "{{ vault_satellite_username }}"
        password: "{{ vault_satellite_password }}"
      when:
        - satellite_server_url is defined
        - vault_satellite_username is defined
        - vault_satellite_password is defined

    - name: Use satellite credentials from AAP
      set_fact:
        host: "{{ lookup('ini', 'url section=sat type=ini file=' + ini_path) }}"
        username: "{{ lookup('ini', 'user section=sat type=ini file=' + ini_path) }}"
        password: "{{ lookup('ini', 'password section=sat type=ini file=' + ini_path)"
      when:
        ini_path | length > 0 # there is something in env variable...

    - name: Install dependency package python requests
      package:
        name: python3-requests

    - name: unregister insights
      command: insights-client --unregister
      args:
        creates: /etc/insights-client/.unregistered
      ignore_errors: true

    - name: unsubscribe from Red Hat
      community.general.redhat_subscription:
        state: absent

    - name: Clean subsriptions
      ansible.builtin.shell:
        cmd: "subscription-manager clean"

    - name: Generate satellite registration command for client
      redhat.satellite.registration_command:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ host }}"
        validate_certs: false
        insecure: true
        force: true
        activation_keys:
          - "RHEL{{ ansible_facts['distribution_major_version'] }}"
      register: command

    - debug:
        var: command.registration_command

    - name: Perform registration
      ansible.builtin.shell:
        cmd: "{{ command.registration_command }}"
