---
- hosts: all
  vars:
    org: Red_Hat
    rhc_state: reconnect
    rhc_organization: "{{ org }}"
    host: "{{ satellite_server_url }}"
  tasks:


    - name: Use satellite credentials from from vault
      set_fact:
        username: "{{ vault_satellite_username }}"
        password: "{{ vault_satellite_password }}"
      when:
        - vault_satellite_username is defined
        - vault_satellite_password is defined

    - name: Install dependency package python requests
      package:
        name: python3-requests

    - name: unregister insights
      command: insights-client --unregister
      args:
        creates: /etc/insights-client/.unregistered
      ignore_errors: true

    - name: unsubscribe from Red Hat
      community.general.redhat_subscription:
        state: absent

    - name: Clean subsriptions
      ansible.builtin.shell:
        cmd: "subscription-manager clean"

    - name: Generate satellite registration command for client
      redhat.satellite.registration_command:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ host }}"
        validate_certs: false
        insecure: true
        force: true
        activation_keys:
          - "RHEL{{ ansible_facts['distribution_major_version'] }}"
      register: command

    - debug:
        var: command.registration_command

    - name: Perform registration
      ansible.builtin.shell:
        cmd: "{{ command.registration_command }}"
