---
#
# This PB can be used to search products repository content for later
# e.g. adding it via redhat.satellite.repository role.
# example:
# ansible-playbook -i hosts  -e @../private-lab/secrets.yml \
#   -e 'product="Red Hat Ansible Automation Platform"' \
#   satellite-repos.yml > repos.log
#
- name: let's play repos
  # hosts: rh-satellite-01.cool.lab
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ansible_ssh_user: root
    print_repo_sets: true
    satellite_server_url: https://rh-satellite-01.cool.lab
    satellite_validate_certs: false
    satellite_organization: Red Hat Cool Lab
    product: Red Hat Enterprise Linux for x86_64
  tasks:
    - name: "Search for possible repository sets of [{{ product }}]"
      redhat.satellite.resource_info:
        username: '{{ satellite_username }}'
        password: '{{ satellite_password }}'
        server_url: '{{ satellite_server_url }}'
        validate_certs: '{{ satellite_validate_certs }}'
        organization: '{{ satellite_organization }}'
        resource: repository_sets
        search: "product_name=\"{{ product }}\""
      register: data
      when: print_repo_sets
    - name: >
        Output found repository sets, see the contentUrl section for possible
        repository substitutions
      debug:
        var: data
      when: print_repo_sets
