---


- name: Register host to IdM
  hosts: all
  vars:
    ipaclient_mkhomedir: true
    ipaclient_ntp_servers:
      - ntp.arrowdemo.se
      - time.cloudflare.com
    ipaclient_ssh_trust_dns: true
    use_inventory_for_hostname: false

  tasks:

    - name: Get the short hostname from inventory
      # Normally there is dot in fqdn, vmware inventory has _ as separator
      set_fact:
        short_name: "{{ inventory_hostname | regex_search('^[^_.]*') }}"
      when: use_inventory_for_hostname

    - name: add to IdM
      vars:
        ipaclients:
          - "{{ short_name | mandatory }}.{{ ipaserver_domain }}"
        state: present
        ipasssd_enable_dns_updates: true
        ipaclient_domain: eu.arrow.lab
        ipaclient_domain: "{{ ipaserver_domain }}"
        ipaclient_realm: "{{ ipaserver_realm }}"
        ipaclient_force_join: true
      include_role:
        name: redhat.rhel_idm.ipaclient
