---

- import_playbook: ensure-vm-state-vmware.yml
  vars:
    memory_mb: 4096
    num_cpus: 2
    state: poweredon
    net_name: coollab-2991
    net_type: static
    ip: "{{ ipaserver_master_ip }}"
    netmask: 255.255.255.0
    gateway: "{{ ipaserver_gw }}"
    short_name: "{{ ipaserver_master_name }}"
    domain: "{{ ipaserver_domain }}"
    dns_servers:
      - "{{ dns_forwarder1_ip }}"
      - "{{ dns_forwarder2_ip }}"
  tags: server

- import_playbook: ensure-vm-state-vmware.yml
  vars:
    memory_mb: 4096
    num_cpus: 2
    state: poweredon
    net_name: coollab-2991
    net_type: static
    ip: "{{ ipaserver_replica_ip }}"
    netmask: 255.255.255.0
    gateway: "{{ ipaserver_gw }}"
    short_name: "{{ ipaserver_replica_name }}"
    domain: "{{ ipaserver_domain }}"
    dns_servers:
      - "{{ dns_forwarder1_ip }}"
      - "{{ dns_forwarder2_ip }}"
  tags: replica

- import_playbook: prepare-rhel.yml
  vars:
    install_pkgs_list:
      - tmux
      - vim
      - insights-client
  tags: prep

- name: setup stuff at IdMs
  hosts:
    - ipaservers
    - ipareplicas
  tasks:

    - name: create hosts entry for idm master
      lineinfile:
        path: /etc/hosts
        regexp: ".*{{ ipaserver_master_name }}.*"
        line: >-
          {{ ipaserver_master_ip }}
          {{ ipaserver_master_name }}.{{ ipaserver_domain }}
          {{ ipaserver_master_name }}

    - name: create hosts entry for idm replica
      lineinfile:
        path: /etc/hosts
        regexp: ".*{{ ipaserver_replica_name }}.*"
        line: >-
          {{ ipaserver_replica_ip }}
          {{ ipaserver_replica_name }}.{{ ipaserver_domain }}
          {{ ipaserver_replica_name }}

- name: setup IdM server
  hosts:
    - ipaservers
  tasks:

    - name: ensure fqdn hostname
      hostname:
        name: "{{ ipaserver_master_name }}.{{ ipaserver_domain }}"
        use: systemd

    - name: apply freeipa role
      include_role:
        name: redhat.rhel_idm.ipaserver
      vars:
        state: present

    - name: permit IdM traffic
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - freeipa-ldap
        - freeipa-ldaps
        - dns
      tags: firewall
  tags: server


- name: setup IdM replica
  hosts: ipareplicas
  tasks:

    - name: ensure fqdn hostname
      hostname:
        name: "{{ ipaserver_replica_name }}.{{ ipaserver_domain }}"
        use: systemd

    - name: apply freeipa role
      include_role:
        name: redhat.rhel_idm.ipareplica
      vars:
        state: present

    - name: permit IdM traffic
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - freeipa-ldap
        - freeipa-ldaps
        - dns
      tags: firewall
  tags: replica

- name: setup IdM DNS configs
  hosts:
    - ipaservers
  tasks:

    - name: setup dns zone
      redhat.rhel_idm.ipadnszone:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ ipaserver_domain }}"
        allow_sync_ptr: true
        dynamic_update: true
        state: present

    - name: setup reverse zone
      redhat.rhel_idm.ipadnszone:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item }}"
        allow_sync_ptr: true
        dynamic_update: true
        state: present
      loop: "{{ dns_reverse_zones }}"
  tags: dns
