---

- import_playbook: ensure-bastion.yml
  vars:
    state: poweredon
    name: rh-bastion-01.coollab

- name: fix inventory
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: debug host ip
      debug:
        var: host_ip
    - name: fix inventory with bastion
      add_host:
        name: "{{ host_ip }}"


- import_playbook: prepare-rhel8.yml
  vars:
    install_pkgs_list:
      - tmux
      - vim
      - insights-client
      - bind-utils
      - ansible
      - git

- name: setup stuff at bastion
  hosts: all
  tasks:

    - name: create source dir
      file:
        path: /root/src
        state: directory
      tags: git

    - name: clone cool lab repo
      git:
        repo: https://github.com/RedHatNordicsSA/cool-lab.git
        dest: /root/src/cool-lab
        update: false
      tags: git

    - name: pull ansible roles
      command:
        cmd: >-
          ansible-galaxy role install
          -r roles/requirements.yml
          -p roles
        args:
          chdir: /root/src/cool-lab

    - name: pull ansible collections
      command:
        cmd: >-
          ansible-galaxy collection install
          -r collections/requirements.yml
          -p collections
        args:
          chdir: /root/src/cool-lab
