---
- name: Install zabbix client
  hosts: all
  become: true
  tasks:

    - name: Set state fact
      ansible.builtin.set_fact:
        _zabbix_state: "{{ lookup('vars', 'zabbix_state') | default('present') }}"

    - name: Install Zabbix repo
      ansible.builtin.dnf:
        # yamllint disable-line rule:line-length
        name: "https://repo.zabbix.com/zabbix/7.4/release/rhel/{{ ansible_facts['distribution_major_version'] }}/noarch/zabbix-release-latest.el{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
        state: present
        disable_gpg_check: true
      when: _zabbix_state != "absent"

    - name: Install zabbix-agent2
      ansible.builtin.dnf:
        name: zabbix-agent2
        state: "{{ _zabbix_state }}"

    - name: Configure Zabbix Agent
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      loop:
        - { key: 'Server', value: "{{ zabbix_server }}" }
        - { key: 'ServerActive', value: "{{ zabbix_server }}" }
        - { key: 'Hostname', value: "{{ ansible_facts['hostname'] }}.{{ ipaserver_domain }}" }
      when: _zabbix_state != "absent"
      notify: Restart zabbix-agent2

    # - name: Open Firewall for Zabbix Agent
    #   ansible.posix.firewalld:
    #     port: 10050/tcp
    #     permanent: true
    #     state: enabled
    #     immediate: true

    - name: Allow Zabbix Agent SELinux outbound (Active)
      ansible.posix.seboolean:
        name: httpd_can_connect_zabbix
        state: true
        persistent: true
      when: _zabbix_state != "absent"

    - name: Disable Zabbix Agent SELinux outbound (Active)
      ansible.posix.seboolean:
        name: httpd_can_connect_zabbix
        state: false
        persistent: true
      when: _zabbix_state == "absent"

    - name: Enable and start zabbix-agent2
      ansible.builtin.service:
        name: zabbix-agent2
        enabled: true
        state: started
      when: _zabbix_state != "absent"

    - name: Register Host in Zabbix Server via API
      # delegate_to: localhost
      become: false
      tags: zab
      vars:
        ansible_host: "{{ zabbix_server }}"
        ansible_user: "{{ username }}"
        ansible_httpapi_pass: "{{ password }}"
        ansible_network_os: zabbix.zabbix.zabbix
        ansible_connection: httpapi
        # ansible_httpapi_port: 80
        ansible_httpapi_use_ssl: false
        # ansible_httpapi_validate_certs: false
        ansible_zabbix_url_path: ""
      zabbix.zabbix.zabbix_host:
        host_name: "{{ ansible_facts['hostname'] }}.{{ ipaserver_domain }}"
        visible_name: "{{ ansible_facts['hostname'] }}.{{ ipaserver_domain }}"
        host_groups:
          - Linux servers
        link_templates:
          - Linux by Zabbix agent
        status: enabled
        state: "{{ _zabbix_state | default(present)}}"
        interfaces:
          - type: agent
            useip: true
            ip: "{{ ansible_facts['default_ipv4']['address'] }}"
            # dns: "{{ ansible_facts['hostname'] }}.{{ ipaserver_domain }}"
            port: "10050"

  handlers:
    - name: Restart zabbix-agent2
      ansible.builtin.service:
        name: zabbix-agent2
        state: restarted
