apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: arrow-lab-eu-ocp-cluster-admins-global-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: arrow-lab-eu-ocp-cluster-admins-global
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: arrow-lab-eu-ocp-cluster-admins-mgmt
