---

lab_admin_ssh_pubkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHV4O/qEctm+YmAY/o0aKk+sgxbFhLMsNN1m4j8FNKSF admin@coollab

vcenter_datacenter: DC3
vcenter_cluster: DC3-cl01
vcenter_folder: EU
vcenter_datastore: fs5200-LUN0

# RHEL subscriptions

rh_subs_username: "{{ vault_rh_subs_username }}"
rh_subs_password: "{{ vault_rh_subs_password }}"
subs_pool: Employee SKU
enabled_repos_rhel:
  '8':
    - rhel-8-for-x86_64-appstream-rpms
    - rhel-8-for-x86_64-baseos-rpms
    - ansible-2-for-rhel-8-x86_64-rpms
  '9':
    - rhel-9-for-x86_64-appstream-rpms
    - rhel-9-for-x86_64-baseos-rpms
    - ansible-automation-platform-2.5-for-rhel-9-x86_64-rpms
  '10':
    - rhel-10-for-x86_64-appstream-rpms
    - rhel-10-for-x86_64-baseos-rpms

# see guide here: https://galaxy.ansible.com/freeipa/ansible_freeipa
dns_forwarder1_ip: 10.1.102.5
dns_forwarder2_ip: 10.1.102.10
dns_reverse_zones:
   - 103.0.10.in-addr.arpa.
   - 109.3.10.in-addr.arpa.
   - 203.3.10.in-addr.arpa.
ipaservers:
  - lab-eu-idm-01.arrowdemo.se
  - arw-eu-idm-02.eu.arrow.lab
ipaserver_master_ip: 10.0.103.25
ipaserver_master_fqdn: lab-eu-idm-01.arrowdemo.se
ipaserver_replica_ip: 10.3.109.25
ipaserver_replica_name: arw-eu-idm-02.eu.arrow.lab
ipaserver_domain: eu.arrow.lab
ipaserver_realm: EU.ARROW.LAB
ipaserver_gw: 10.0.103.1
ipaadmin_principal: admin
ipaclient_ntp_servers: true
ipaclient_mkhomedir: true
ipaadmin_password: "{{ vault_ipaadmin_password }}"
ipasssd_enable_dns_updates: true

# define the idm host groups
hostgroups:
  - name: infra
    description: Infrastructure Hosts
    hosts:
      - lab-eu-idm-01.arrowdemo.se
      - arw-eu-idm-02.eu.arrow.lab
      - arw-eu-bastion-01.eu.arrow.lab
  - name: ipaservers
    description: IdM cluster hosts
    hosts:
      - arw-eu-idm-01.arrowdemo.eu
      - arw-eu-idm-02.eu.arrow.lab

aap_username: admin
aap_ldap_bind_username: aap_ldap
aap_hostname: aap.eu.arrow.lab

ah_hostname: aap.eu.arrow.lab
ah_username: "admin"
ah_password: "{{ aap_admin_password }}"
# redhat automatin hub
ah_oauthtoken: "{{ vault_aap_automationhub_token }}"
# local private aap automatin hub
# pah_oauthtoken: "{{ vault_aap_private_automationhub_token }}"
ah_validate_certs: false

satellite_ip: 10.3.103.12
satellite_server_url: https://rh-satellite-01.eu.arrow.lab
satellite_foreman_pubkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9PZeSxGk7VRoZOiTtTku5zZcvHM+vyHQ/4BnmrI4K4kWBEXXK+y+PtbpXH/9phNro+jyM5uP1qdGdAoZbYVDaFuCZ3iaHCOStzkfeXyJuq9GaNzFT5Gcq6lc0EPMqb8Nz8ntCMdPncMnWMmjGUU+oAgnp/TW6738LgK4C7QjzT9UZ2Sai2MERh9zxOAZ78tDeaZYvu2qTRZT0H9DCihq0BzTiRraT5DqdLkN9/hVtyC55M5IT1UzJQrRtxmp8kxGKwYnNcdKNDSSxkkW5M2M9fQ21oIVrJHYuweytW+zeyt76ritB6qsfVZZF8i4lkbp74pMace8Kai4s/9hYtwlTsBFoM3cOMr9rxOLZNwdVHwJaYQoSZYC9sb3ZueM9+Ti3jmBm1pOaP5fJtZzKpn3IbeudrMvSLtYO/kP/bp+bszKFLuVwBLqkOWXStI23IB7efDWkJXXcQQhi3iLtDdIHOes50fz46XnHDwKfuftbF08sKOLtwlCKIAwODxHhk7M= foreman-proxy@rh-satellite-01.eu.arrow.lab
zabbix_server: zabbix.eu.arrow.lab
