---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhacm-mco-clusterrole
rules:
- apiGroups: ["observability.open-cluster-management.io"]
  resources: ["multiclusterobservabilities"]
  verbs: ["get", "watch", "list", "patch", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhacm-mco-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  kind: ClusterRole 
  name: rhacm-mco-clusterrole
  apiGroup: rbac.authorization.k8s.io
