---

enabled_users:
  #
  # Red Hat users
  #
  - name: apelline
    first: Aki
    last: Pellinen
    password: "coolpw"
    userauthtype: password
    # yamllint disable-line rule:line-length
    sshpubkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOczcHwu8u3ODTNxkNqKR7liLC0BOxNs642fW7qksCJx apelline@redhat.com

  - name: earvonen
    first: Eero
    last: Arvonen
    password: "coolpw"
    # yamllint disable-line rule:line-length
    sshpubkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDh1I/jpC7E6WyDJYw7LORehpd/50YtmMeE1bQaCX6KG3PfBFdKyu0VtssuevU6WS4zfDRruNNpoukUdbsL7dWQqgXQQB0hbPykDd8iqaC4bqKIYAqYEBv6anHppnr39hvKtLrmNDMAVwMNFdns3dFSUueg1PcdfyNNQ8qnKu1Mq9JmAKsb8WwJ8cdwpRMeGujU5QUAJF7FicHgftLyhKJQbgsN+KNWbwRTSTknjjot2e869mSV9qwo58iZZLt1BUyofVQch7a5h7/PXxXjuYjHmXAgK5fXRqktPqqSB0rqgSApIv5IOfm02zbOt5EopVLijLSTTxWnM+gTHETYBg7nmYdMUztBmbbKeGvsw5UzIMO4qHYaqCWRYn6Oq/Shtb07LrASD2vVthe57qg2MR7QwmoiVXxt+Fpxx4v2nzjMcs2lTWigie4COiS7jatu/rU7JYQEouwmxOy1JFj1p51e7u0fplAx8JhdklQZ1aqgDQcacdC0YOT7yfJ5jiKeIe0=

  - name: ikke
    first: Ilkka
    last: Tengvall
    password: "coolpw"
    # yamllint disable-line rule:line-length
    sshpubkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC577GzJaVha0u0byNEFLDbGQhMkPSyXeT9gqIfZMKIxgh9PhOjpHl739lcdbsbgiUVAjZYI7M3PwuGghYTZpk2amJEZXUrul2MQudEc5tUX9wbpdKx9PEhzCywynRN+ZWGK15R5uVyc8mhqbvE0xQnkX0d+/eh+K8reFw451rPJuXrbbk13x/KBs/WqjEGCe6Yto/BotRRadpxTP5gPTxs/MIZ9LZC5EjmuOxDVt1xNROUNdD7gdK8DdpAHK72OoaT5ooc3Zq9uum4sYhCc611IGMNy2yjaYsJWWiVpDFy+APs5u9oK7wdtYFZwhf6B1O3U1X21CoaU8nJsFxJmI1g32IaAfh18sGiTBKKu8vYfF1y2eHa0I/App5WI+H5BS9WV7QyW5s7FQQ9R0okZ3kWbiGj8tVcVdTviwKmNm/7FtED6vPDe9ji+ou56YyzX7sd8ZFZjCX4rG9ZfpCzwsCCRdYHcKEyTIM5is9aggSUVWIkhdD9IKKsJEuW2ZCo8zpVMqSKm4G05tieIAGGr546m1OiTVBFVzuhYuTmwGuVfR0szoDCV6nOc1vcZMLyWYM5zWZRMuCw6NMzMuL+ot0JXyVKtgfFt4q5Q+Ha87jYXsiLOezsTiycgG1c/HmF4NxfWHt8nkDP/hQI0ESb1AKqxqp3++mCciHd1PlE/Y1CaQ==

  - name: sara
    first: Sara
    last: Banderby
    password: "coolpw"
    # yamllint disable-line rule:line-length
    sshpubkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCMeCQ/mpzMpapDaP17Ja6SW//nWH3vUqQbkizWjZiTIZOGT41sNbsuREcw02a56n/2VCcO0yE2LykbXFTFx0hf6x7Fk0j+RGop19laReR5U0WRNK7lK76aomxrPIgKLxs/ReS5QBNX1UUnsfw/LW0nvEq4So3eVhNePVS3RJchNjPcOLrorAvj7mW+RLURczQIJLHeR99PJVRD/tEwaaKr43aGu/RKHrmJl/3dZ1E6N2D89hZP/Mf3li0fFOSCNHS4bJ8uMAp5Z6Bs8/1QvRYCy+JVix+VxX5dNc+NS2r3D0EidHxvvsvef7PvE/s7j2Z28vdptLgSPYaOcc6klxHGJxQIxGpI42m/0kM7TzlBzkPaOM70dyt3FegYFNB0UYYVUF5UGVFHYfIOStZAnWDdf8CVwkR1z71haYAy7qAitVL3/4zJMttCm8o7nYPVGEK2T8717XAA+ghvjcPjhNMyAZF5v0bvT4OUYcQ8vNtQmZbiOK3qeB3kaCd8iU84PL8= elajoie@redhat.home.lab

  - name: suvmitra
    first: Suvendu
    last: Mitra
    password: "coolpw"
    # yamllint disable-line rule:line-length
    sshpubkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCuZqgLjI/QB1iI+dVEj8QZg1+Tar/lLDeChmOxQ8DhRuOaEgxSLWf2AMLuiqsVvVkoClFjmTPGAPb2qvfCMYxFf87U8CVzzKyCFXojOqo0jCQXJQQ/DczCtcihjDaXWdoioi01k2WIKecitc+lKKT2FLKimqSvlgBqY6fou+sZP3rCtrrcx0kYqZiXrvD6C9eB2ZyupZtWUBdL5KwGS/mY+749ORkA378YOsHwbZdbQMuepJCVIfdArcIgiYBzVGMf7CtNc1H9VU90A3i6hQrq8GNkWXJMlyi4kpYwsxTAE4MHeRVomYSFgxRb3tFX9tq3AmqPNKz6He10L6TPGHydzZR5RsvdEwbGf2KWFClOvZOLkw5YKrqa9ehQQozkLt/6C05esju25uRMujw2Y5z5DAFyIK/lPSk1HML1Ldp0Mx8fCsq+xQifExzyo/euzgViVCbcrqTHU38+IbD2RwVNFsr6LyW6J9w0nmDK7mMVgBMfDERriZd798xKP3w9prk= suvmitra@MacBook-Pro

  - name: tsohlber
    first: Tommi
    last: Sohlberg
    password: "coolpw"
    # yamllint disable-line rule:line-length
    sshpubkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJ2cHjhSVd4KNUYVultbOUtUNqYsdEd+FGW90vbAXdAPt5DJ6+11NWIvSY8BHs0U84zh5MLsGzZYqmpgdYmPUuD0BCvUhoNdaZBxtn1upVl5ep+8qBWnNiSevxmBoK1xnuSexNOiCeV4JBHzBgLRCy92R8kzc8eE6XmsVZn+aFDwC/ZUa3LVvVTwreM1LWYxDMPPla25iq0R8Q0+aerpXX+/8aujevat+EOp9EuJ3J87T1KnBl1yV0s3mbLvwQHtCnBUNDSpCMbRJZmj1JpX4Hf1Qh60lMT0mFiV3d1WUDLGdQB6JciTo/I/J5nUdTxGZ+IQvOaud9/+562mD26z43 tsohlber@MacBook-Pro

  #
  # Arrow users
  #
  - name: teli
    first: Terje
    last: Lindholm
    password: "coolpw"
    # yamllint disable-line rule:line-length
    sshpubkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/A45JyRp8OOvC95Db42mz7KocV2x/zuOqmuQTSY0A9QhoBlIRJEhb9PaQCLy43u/chBEaqPKgtp7JphXJf6rr6vN5aLofeEGQvb/z+obdFKxobQKmUCm6BJK6HvcK/unvimtb9Ub7c1UGJ+Iy+Hg7HZJGbjrHZCjLjviFsrkMlikvNB+hZO/B56f5ewQVbtPJ9RzDVs3ut/AciEaYRVsRCZWylP4eIDWxqfQhTfC3ER6Xe0CSoIs94Nhtug0wZzIrP+UHtb7ryQaKd9PkLHReBH4nJ+jz+syJAxwZxPvDkQUKofPtxgeSdLp30q8JFYTkStbRx05pw0kvaGmO2qD4V16W1ZApzbg3j64/tDs+P0VjWnZr0SklvBkcY84HMQ+Zq287N3T0SU4yp1CrnFNzMv82kpGJL8z5rBQYe2TrOxt6iJqHSd1Dm8QT47XLenj53khPp+5dJWyo9Dwae3s1MoDio4r8ZT2ASAqmNkntMWMaoEAsdZrYIidx63rY2tk= a91466@C02DN3WNMD6R

    name: thomar
    first: Thomas
    last: Marko
    password: "coolpw"
    # yamllint disable-line rule:line-length
    sshpubkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID9iOvCQWkwvRR4vZu7OFN7jtaBg/+gp9yt8PwA3eQPf

idm_admins:
  - ikke
  - teli
  - thomar

aap_admins:
  - ikke
  - teli
  - thomar
  - tsohlber

rh_ops:
  - ikke
  - tsohlber

arrow:
  - teli
  - thomar

arrow_ops:
  - teli
  - thomar

odh_admins:
  - ikke
  - teli
  - thomar
  - sara

developers:
  - earvonen
  - ikke
  - sara
  - teli
  - thomar
