---
- name: Receive stuff via webhook
  hosts: all
  sources:
    - name: Listen to any webhooks
      eda.builtin.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Apache problems
      # condition: event.meta is defined and event.payload.event_name is match("Apache.*") and (event.payload.event_name is match(".*not running.*") or event.payload.event_name is match(".*is down.*"))
      condition: event.meta is defined and event.payload.event_name is match("Apache .httpd. is not running on .*")
      actions:
        - debug:
            var: event
        - run_workflow_template:
            name: "AIOps Webserver Rescue Workflow"
            organization: "Red Hat"
            job_args:
              limit: "{{ event.payload.host_host.split('.')[0] }}"
              extra_vars:
                short_name: "{{ event.payload.host_host.split('.')[0] }}"
                target: "{{ event.payload.host_host }}"
                problem: "{{ event.payload.trigger_name }}"
    - name: debug anything
      condition: event.meta is defined
      action:
        debug:
          var: event
