---


# - name: Register host to IdM
#   hosts: ipaclients
#   vars:
#     ipaclient_mkhomedir: true
#     ipaclient_ntp_servers:
#       - ntp.arrowdemo.se
#       - time.cloudflare.com
#     ipaclient_ssh_trust_dns: true

#   tasks:

- name: setup hostname
  hostname:
    name: "{{ short_name | mandatory }}.{{ ipaserver_domain }}"
    use: systemd

- name: create hosts entry for idm master
  lineinfile:
    path: /etc/hosts
    regexp: ".*{{ ipaserver_master_name }}.*"
    line: >-
      {{ ipaserver_master_ip }}
      {{ ipaserver_master_name }}.{{ ipaserver_domain }}
      {{ ipaserver_master_name }}

- name: create hosts entry for idm replica
  lineinfile:
    path: /etc/hosts
    regexp: ".*{{ ipaserver_replica_name }}.*"
    line: >-
      {{ ipaserver_replica_ip }}
      {{ ipaserver_replica_name }}.{{ ipaserver_domain }}
      {{ ipaserver_replica_name }}

- name: add to IdM
  vars:
    state: present
    ipasssd_enable_dns_updates: true
    # ipaclient_force: true
  include_role:
    name: freeipa.ansible_freeipa.ipaclient

# - name: add to dns
#   freeipa.ansible_freeipa.ipahost:
#     action: member
#     state: present
#     name: "{{ ansible_fqdn }}.{{ ipaserver_domain }}"
#     ipa