---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stackrox

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/perNode/collector/collection
        value: 'NoCollection'