---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ansible-automation-platform
spec:
  project: default
  source:
    repoURL: https://github.com/RedHatNordicsSA/cool-lab.git
    targetRevision: arrowlab
    path: ocp-configs/gitops/mgmt-eu-arrow-lab/ansible-automation-platform/instance/overlays/default
  destination:
    server: https://kubernetes.default.svc
    namespace: ansible-automation-platform
  syncPolicy:
    automated:
      allowEmpty: true
