---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-gitops-instance
spec:
  project: default
  source:
    repoURL: https://github.com/RedHatNordicsSA/cool-lab.git
    targetRevision: arrowlab
    path: ocp-configs/gitops/mgmt-eu-arrow-lab/openshift-gitops-operator/instance/overlays/default
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      allowEmpty: true
