---

apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  labels:
    {{- include "ldap.labels" . | nindent 4 }}
spec:
  identityProviders:
  - name: Red Hat IdM
    mappingMethod: claim
    type: LDAP
    ldap:
      attributes:
        id:
        - dn
        email:
        - mail
        name:
        - cn
        preferredUsername:
        - uid
      bindDN: '{{ .Values.secrets.ldap.bindDN }}'
      bindPassword:
        name: ldap-secret
      ca: 
        name: ca-config-map
      insecure: false
      url: "{{ .Values.secrets.ldap.url }}/cn=users,cn=accounts,dc=cool,dc=lab?uid"
